(function ensightenInit(){var ensightenOptions = {client: "mscertain", clientId: 1955, publishPath: "prod", isPublic:1, serverComponentLocation: "nexus.ensighten.com/mscertain/prod/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/mscertain/prod/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "false", enablePagePerfBeacon : "false", registryNs : "ensBootstraps", generatedOn : "Fri Apr 29 21:19:10 GMT 2016", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(g){function m(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function n(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function p(){for(var a=b.dataDefinitionIds.length,e=!0,d=0;d<a;d++){var c=b.dataDefinitions[b.dataDefinitionIds[d]];if(!c||
null==c.endRegistration){e=!1;break}}e&&b.callOnDataDefintionComplete()}var c={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};c.version="1.26.0";c.nexus=g.nexus||"nexus.ensighten.com";c.rand=-1;c.currSec=(new Date).getSeconds();c.options={interval:g.interval||100,erLoc:g.errorLocation||c.nexus+"/error/e.gif",scLoc:g.serverComponentLocation||c.nexus+"/"+g.client+"/serverComponent.php",sjPath:g.staticJavascriptPath||c.nexus+"/"+g.client+"/code/",alLoc:g.alertLocation||c.nexus+"/alerts/a.gif",
publishPath:g.publishPath,isPublic:g.isPublic,client:g.client,clientId:g.clientId,enableTagAuditBeacon:g.enableTagAuditBeacon,scUseCacheBuster:g.scUseCacheBuster,beaconSamplingSeedValue:g.beaconSamplingSeedValue||-1};c.ruleList=[];c.allDeploymentIds=[];c.runDeploymentIds=[];c.exceptionList=[];c.ensightenVariables={};c.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var b=0;b<a.dependencies.length;b++)if(!1===a.dependencies[b]())return;
a.execute()}};m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;c.DependencyNotAvailableException=m;n.prototype=Error();n.prototype||(n.prototype={});n.prototype.constructor=n;c.BeaconException=n;c.checkForInvalidDependencies=function(a,e,d,l){for(a=0;a<d.length;a++)if("DEPENDENCYNEVERAVAILABLE"===d[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new c.DependencyNotAvailableException(l[a])),e&&-1!==e&&c.allDeploymentIds.push(e),
!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.sampleBeacon=function(){var a=!1;try{var b=(c.currSec||0)%20,d=c.options.beaconSamplingSeedValue;-1===d?a=!0:0!==b&&0===d%b&&(a=!0)}catch(l){}return a};b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+c.options.scLoc,!1,a||!0,c.options.scUseCacheBuster)};b.setVariable=function(a,b){c.ensightenVariables[a]=
b};b.getVariable=function(a){return a in c.ensightenVariables?c.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<c.ruleList.length;a++)c.test(c.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();c.exceptionList.push(a);a=window.location.protocol+"//"+c.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||
a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(c.options.clientId||-1)+"&client="+encodeURIComponent(c.options.client||"")+"&publishPath="+encodeURIComponent(c.options.publishPath||"")+"&rid="+encodeURIComponent(b.currentRuleId||-1)+"&did="+encodeURIComponent(b.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=b.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);
b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(a){window[ensightenOptions.ns].reportException(a)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&c.runDeploymentIds.push(this.deploymentId),b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&-1!==a.id)return!1;c.ruleList.push(a);-1!==a.deploymentId&&
c.allDeploymentIds.push(a.deploymentId);b.testAll();return!0};b.getRule=function(a){for(var b=0;b<c.ruleList.length;b++)if(c.ruleList[b].id===a)return c.ruleList[b];return!1};

b.getAllDeploymentIds=function(){return c.allDeploymentIds};b.getRunDeploymentIds=function(){return c.runDeploymentIds};b.hasRuleRun=function(a){return(a=b.getRule(a))?a.executionData.hasRun:!1};c.toTwoChar=function(a){return(2===a.toString().length?
"":"0")+a};b.Alert=function(a){var b=new Date,b=b.getFullYear()+"-"+c.toTwoChar(b.getMonth())+"-"+c.toTwoChar(b.getDate())+" "+c.toTwoChar(b.getHours())+":"+c.toTwoChar(b.getMinutes())+":"+c.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);this.type=encodeURIComponent(this.type)};b.generateAlert=function(a){a=
b.imageRequest(window.location.protocol+"//"+c.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+c.options.clientId+"&client="+c.options.client+"&publishPath="+c.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};b.insertScript=function(a,e,d,l){var h=document.getElementsByTagName("script"),f;l=void 0!==l?l:!0;if(void 0!==
e?e:1)for(f=0;f<h.length;f++)if(h[f].src===a&&h[f].readyState&&/loaded|complete/.test(h[f].readyState))return;if(d){d=1==d&&"object"==typeof b.scDataObj?b.scDataObj:d;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));e=window.location.href;"object"===typeof d&&d.PageID&&(e=d.PageID,delete d.PageID);if("object"===typeof d)for(f in d){f=~e.indexOf("#")?e.slice(e.indexOf("#"),e.length):"";e=e.slice(0,f.length?e.length-f.length:e.length);e+=~e.indexOf("?")?"&":"?";for(k in d)e+=k+"="+d[k]+"&";
e=e.slice(0,-1)+f;break}a+="?";l&&(a+="r="+c.rand+"&");a+="ClientID="+encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(e)}(function(a,b,e){var d=b.head||b.getElementsByTagName("head");setTimeout(function(){if("item"in d){if(!d[0]){setTimeout(arguments.callee,25);return}d=d[0]}var a=b.createElement("script");a.src=e;a.onload=a.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.insertBefore(a,d.firstChild)},0)})(window,document,a)};b.loadScriptCallback=function(a,
b,d){var c=document.getElementsByTagName("script"),h;d=c[0];for(h=0;h<c.length;h++)if(c[h].src===a&&c[h].readyState&&/loaded|complete/.test(c[h].readyState))try{b()}catch(f){window[ensightenOptions.ns].reportException(f)}finally{return}c=document.createElement("script");c.type="text/javascript";c.async=!0;c.src=a;c.onerror=function(){this.addEventListener&&(this.readyState="loaded")};c.onload=c.onreadystatechange=function(){if(!this.readyState||"complete"===this.readyState||"loaded"===this.readyState){this.onload=
this.onreadystatechange=null;this.addEventListener&&(this.readyState="loaded");try{b.call(this)}catch(a){window[ensightenOptions.ns].reportException(a)}}};d.parentNode.insertBefore(c,d)};b.unobtrusiveAddEvent=function(a,b,d){try{var c=a[b]?a[b]:function(){};a[b]=function(){d.apply(this,arguments);return c.apply(this,arguments)}}catch(h){window[ensightenOptions.ns].reportException(h)}};b.anonymous=function(a,e){return function(){try{b.currentRuleId=e?e:"anonymous",a()}catch(d){window[ensightenOptions.ns].reportException(d)}}};
b.setCurrentRuleId=function(a){b.currentRuleId=a};b.setCurrentDeploymentId=function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],code:a});
else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindOnGetServerComponent=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var e,d=0;d<a.length;++d)if(e=b.getRule(parseInt(a[d],10)),!e||!e.executionData.hasRun)return!1;return!0};b.bindDependencyImmediate=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMLoaded=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,
l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});
f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===
typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var e=a.length,d=0;d<e;d++){var c=a[d];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(c)&&b.dataDefinitionIds.push(c);else{for(var h=!1,f=b.dataDefinitionIds.length,g=0;g<f;g++)if(b.dataDefinitionIds[g]===c){h=!0;break}h||b.dataDefinitionIds.push(c)}}b.pageSpecificDataDefinitionsSet=!0;p()};b.DataDefinition=function(a,b){this.id=
a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,e){var d=b.dataDefinitions[e];d||(d=new b.DataDefinition(e,a),b.dataDefinitions[e]=d);d.startRegistrationTime||(d.startRegistration(),d.registrationFn(),d.endRegistration());b.pageSpecificDataDefinitionsSet&&p()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=
!0;b.testAll()};b.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,d=a.length;b<d;b++)if(a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=
a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=
function(){return window[ensightenOptions.ns].executionState.DOMLoaded};b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var q=function(){var a=[],b=!1,d=!1;return{add:function(c){b&&!d?c():"function"==typeof c&&(a[a.length]=c)},exec:function(){d=!0;do{var c=a;a=[];b=!0;for(var g=0;g<c.length;g++)try{c[g].call(window)}catch(f){window[ensightenOptions.ns].reportException(f)}}while(0<a.length);d=!1},haveRun:function(){return b}}};b.new_fArray=
function(){return q()};c.timer=null;(function(){function a(a,b){return function(){a.apply(b,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var c=log4javascript.getDefaultLogger();b.log=a(c.info,c);b.debug=a(c.debug,c);b.info=a(c.info,c);b.warn=a(c.warn,c);b.error=a(c.error,c)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?
c.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&(clearInterval(c.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",
function(){window[ensightenOptions.ns].callOnDOMLoaded()}));"true"===c.options.enableTagAuditBeacon&&b.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],e,d,l,h,f=0;f<c.ruleList.length;++f)d=c.ruleList[f],l=d.executionData.hasRun?"1":"0",h=d.deploymentId.toString()+"|"+d.id.toString()+"|"+l,a.push(h);e="["+a.join(";")+"]";var m=window.location.protocol+"//"+c.nexus+"/"+encodeURIComponent(g.client)+"/"+encodeURIComponent(g.publishPath)+
"/TagAuditBeacon.rnc?cid="+encodeURIComponent(g.clientId)+"&data="+e+"&idx=0&r="+c.rand;b.imageRequest(m)}catch(n){b.currentRuleId=-1,b.currentDeploymentId=-1,a=new c.BeaconException(n),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,c.options.interval);return b}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var g=window.performance;if(g){var g=g.timing||{},m="",n=g.navigationStart||0,p,c={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",
fetchStart:"fs",loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"},m="&ns="+encodeURIComponent(g.navigationStart),b;for(b in c)void 0!==g[b]?(p=g[b]-n,m+="&"+c[b]+"="+(0<p?encodeURIComponent(p):0)):m+="&"+c[b]+"=-1";window[ensightenOptions.ns].timing=m;b=ensightenOptions.nexus||"nexus.ensighten.com";g=ensightenOptions.staticJavascriptPath||
"";m=g.indexOf(".com/");n=g.indexOf("/code/");g=g.substring(m+4,n)+"/perf.rnc";g+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+b+g)}}});
		Bootstrapper.dataDefinitionIds = [];Bootstrapper.bindDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;jQuery(".r123FormSubmit").on("mousedown",function(){jQuery(this).attr({"ms.cmptyp":"button","ms.cmpgrp":"body","ms.cmpnm":"form-submit","ms.ea_action":"reg","ms.ea_offer":"lev","ms.title":"register_now","ms.interactiontype":"2"})})},1179502,361695);
Bootstrapper.bindDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var pagetype=jQuery('meta[name\x3d"ms.sitesec"]').attr("content");var site=jQuery('meta[name\x3d"ms.ea_targetcampaign"]').attr("content");var e=document.createElement("script");e.async=true;e.src="https://ad.atdmt.com/m/a.js;m\x3d11087206992497;cache\x3d"+Math.random()+"?";var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(e,s);function atlasTrack(uri){var timestamp=
new Date;var qs="\x26random\x3d"+Math.ceil(Math.random()*99999999)+timestamp.getUTCFullYear()+timestamp.getUTCMonth()+timestamp.getUTCDate()+timestamp.getUTCHours()+timestamp.getUTCMinutes()+timestamp.getUTCSeconds()+timestamp.getUTCMilliseconds();var uriPlus="//ad.atdmt.com/m/a.js;m\x3d11087206992497?event\x3d"+uri+qs;var script=document.createElement("script");script.type="text/javascript";script.src=uriPlus;document.getElementsByTagName("head")[0].appendChild(script)}if(site==="CP2-WE-2C-216434_v2")if(pagetype===
"LandingPage")atlasTrack("DND_Consumer_ITA_Ini_Con_NuvolarosaFORM_LP");else{if(pagetype==="ThankYouPage")atlasTrack("DND_Consumer_ITA_Ini_Con_NuvolarosaFORM-THKU_CON")}else if(site==="CP2-WE-2C-216434_v1")if(pagetype==="LandingPage")atlasTrack("DND_Consumer_ITA_Ini_Con_NuvolarosaFORM_LP");else{if(pagetype==="ThankYouPage")atlasTrack("DND_Consumer_ITA_Ini_Con_NuvolarosaFORM-THKU_CON")}else if(site==="CP2-WE-2C-216434_v3")if(pagetype==="LandingPage")atlasTrack("DND_Consumer_ITA_Ini_Con_NuvolarosaFORM_LP");
else if(pagetype==="ThankYouPage")atlasTrack("DND_Consumer_ITA_Ini_Con_NuvolarosaFORM-THKU_CON")},1354607,383573);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.AF=function(){var g={data:{},_dataConfig:{},logHistory:[],debug:!0,dataObj:function(a){var b=a?[]:"";b.finalized=!1;b.type=a;return b},validateInput:function(a){if("object"!==typeof a||"number"!==typeof a.length)return this.log("Error, input must be type Array");/set|push|call|eval|finalize|join/.test(a[0])||this.log("Error, '"+a[0]+"' is not a valid command");
return!0},storeData:function(a,b,d,c,e){e=this.getConfig(b,d,e);b=this.data[b][d];if(e.finalized)return this.log("Error, cannot modify finalized key '"+d+"'"),b;if("undefined"!==typeof b&&e.multi)return"join"==a?b=b.concat(c):b.push(c),b;e.multi?(d=[c],"join"==a&&(d=[].concat(c))):d=c;return d},getConfig:function(a,b,d,c){a=this._dataConfig[a]||{};c={};return"undefined"==typeof a[b]?(c.multi=d,c.finalized=!1,c):a[b]},store:function(a,b,d,c,e){this.data[b]=this.data[b]||{};this.data[b][d]=this.storeData(a,
b,d,c,e);return this.data[b][d]},parseCode:function(a){return((a||function(){})+"").replace(/^function\s*\(\s*\)\s*\{|\}$/g,"")},callFn:function(a,b,d,c){if("function"==typeof a)if(d)"undefined"!=typeof window.execScript?window.execScript(this.parseCode(a)):eval.call(window,this.parseCode(a));else return a.apply(window,c);else if("function"==typeof this.data[a][b])if(d)"undefined"!=typeof window.execScript?window.execScript(this.parseCode(this.data[a][b])):eval.call(window,this.parseCode(this.data[a][b]));
else return c="object"==typeof c&&"number"==typeof c.length?c:[],this.data[a][b].apply(this.data[a],c);else return this.log("Error, '"+b+"' is not a function")},parse:function(a){if(this.validateInput(a)){a=Array.prototype.slice.call(a,0);var b=a.shift(),d=a.shift(),c=a.shift(),e=a[0];if(/set|push|join/.test(b))return this.store(b,d,c,e,/push|join/.test(b));if(/call|eval/.test(b))return this.callFn(d,c,"eval"==b,a);if("finalize"==b)return a=this._dataConfig[d]=this._dataConfig[d]||{},a=a[c]||{multi:!1},
a.finalized=!0,this._dataConfig[d][c]=a}},log:function(a){this.logHistory.push(a);return this.debug&&"object"==typeof console?console.log(a)&&!1:!1}};if("object"==typeof Bootstrapper.AF&&"[object Array]"!==Object.prototype.toString.call(Bootstrapper.AF))return Bootstrapper.AF;if("[object Array]"===Object.prototype.toString.call(Bootstrapper.AF))for(var h=Bootstrapper.AF,f=0;f<h.length;f++)try{g.parse(h[f])}catch(k){}return{push:function(a){return g.parse(a)}}}();Bootstrapper.ajaxListener=function(){var listeners=
{},listener=function(a,b){var detected=[],selector=a||function(){},attach=b||function(node){};return function(){if(typeof selector=="function"&&typeof attach=="function"){var n=selector();if(typeof n=="object")if(typeof n.length!="undefined"){n=Array.prototype.slice.call(n,0);for(var i=n.length-1;i>=0;i--)for(var j=0;j<detected.length;j++)if(n[i]==detected[j])n.splice(i,1);for(var i=0;i<n.length;detected.push(n[i++]));for(var i=0;i<n.length;attach.call(n[i],n[i++]));}else{for(var i=0;i<detected.length;i++)if(n==
detected[i])return;detected.push(n);attach.call(n,n)}}}},_public={create:function(x,y){do var a=parseInt(Math.random()*1E5)+"";while(listeners[a]);listeners[a]=listener(x,y)}};setInterval(function(){for(key in listeners)listeners[key]()},500);return _public}();Bootstrapper.Cookies=function(){return{domain:"microsoftevents.com"||location.hostname,get:function(a,c){for(var b=document.cookie.split(";"),d=0;d<b.length;d++){var e=b[d].replace(/^\s+/,"").split("\x3d");if(e[0]==a)return c?e[1]:decodeURIComponent(e[1])}return""},
set:function(a,c,b){document.cookie=a+"\x3d"+encodeURIComponent(c)+(b?";expires\x3d"+b:"")+";path\x3d/;domain\x3d"+this.domain;return this.get(a)==c},test:function(a){return this.get(a)?!0:!1}}}();Bootstrapper.dataManager=function(){var _private={data:{},add:function(o){if(typeof o=="object"&&o.id){o.get=function(e){return Bootstrapper.dataManager.getDataElement(this.id,e)};this.data[o.id]=o}},getObj:function(i){if(i)return _private.data[i];return _private.data},getDataElement:function(i,e){if(typeof this.data[i]==
"undefined")return"";var dataObj=this.data[i].data,retVal;if(typeof dataObj=="object"){if(typeof dataObj[e]=="undefined")return"";dataObj=dataObj[e];if(typeof dataObj.get=="string"){var d=eval(dataObj.get);if(typeof dataObj.mod=="string"&&dataObj.mod!==""){var m="(function(){ return "+(dataObj.mod===""?"this":dataObj.mod)+";})";retVal=eval(m).call(d)}else if(typeof dataObj.mod=="function")retVal=dataObj.mod.call(d,d);else retVal=d}else if(typeof dataObj.get=="function"){var d=dataObj.get.call(this.data[i]);
if(typeof dataObj.mod=="string"&&dataObj.mod!==""){var m="(function(){ return "+(dataObj.mod===""?"this":dataObj.mod)+";})";retVal=eval(m).call(d)}else if(typeof dataObj.mod=="function")retVal=dataObj.mod.call(d,d);else retVal=d}return retVal}},getDataLayer:function(i){var retObj={};var dataObj=this.data[i].data;for(key in dataObj)try{retObj[key]=this.getDataElement(i,key)}catch(e){retObj[key]=null}return retObj},getAllData:function(){var data=this.data,retObj={_d:{}};for(var key in data){retObj._d[key]=
{};var d=this.getDataLayer(key);for(var k in d){retObj[k]=d[k];retObj._d[key][k]=d[k]}}return retObj},getData:function(i){if(i)return this.getDataLayer(i);else return this.getAllData()},addDataElement:function(layerId,name,o){if(typeof this.data[layerId]=="object"&&typeof name=="string"&&typeof o=="object"){var d=this.data[layerId];d.data[name]=o}}},_public={push:function(dl){_private.add(dl)},getObj:function(i){return _private.getObj(i)},getData:function(i){return _private.getData(i)},getDataElement:function(i,
e){return _private.getDataElement(i,e)},addDataElement:function(layerId,name,o){return _private.addDataElement(layerId,name,o)}};return _public}();Bootstrapper.dataManager.map=function(){return{define:function(n,d){if(Bootstrapper.data)for(i in d){var v=typeof d[i]=="string"?Bootstrapper.data.extract(d[i]):d[i]();Bootstrapper.data.dataManagerPush(i,v,n)}}}}();window.$data=function(a,b){if(typeof b=="string")try{return Bootstrapper.dataManager.getDataElement(a,b)}catch(e){}else if(typeof a=="string")return Bootstrapper.dataManager.getData()[a]||
"";return""};Bootstrapper.bindOnGetServerComponent(function(){var DL=Bootstrapper.dataManager&&Bootstrapper.targetingExtension?Bootstrapper.dataManager.getData():{};if(~document.cookie.indexOf("VTP:enabled"))DL["ensightenVT"]=1;if(Bootstrapper.scDataObj)for(i in DL)Bootstrapper.scDataObj[i]=DL[i]});var ns=window[ensightenOptions.ns];ns.VTconfig=ns.VTconfig||{};ns.VTconfig["DM"]=this.deploymentId;Bootstrapper.dataManager.pushObject=function(obj,id,name){Bootstrapper.dataManager.push({name:name||id,
id:id,data:{}});for(var k in obj)if(obj[k]&&typeof obj[k]!=="function")Bootstrapper.dataManager.addDataElement(id,k,{name:k,get:function(o,key){return function(){return o[key]}}(obj,k)})};(function(){function s(e,t,n){var r=t=="blur"||t=="focus";e.element.addEventListener(t,n,r)}function o(e){e.preventDefault();e.stopPropagation()}function u(t){if(e)return e;if(t.matches)e=t.matches;if(t.webkitMatchesSelector)e=t.webkitMatchesSelector;if(t.mozMatchesSelector)e=t.mozMatchesSelector;if(t.msMatchesSelector)e=
t.msMatchesSelector;if(t.oMatchesSelector)e=t.oMatchesSelector;if(!e)e=p.matchesSelector;return e}function a(e,n,r){if(n=="_root")return r;if(e===r)return;if(u(e).call(e,n))return e;if(e.parentNode){t++;return a(e.parentNode,n,r)}}function f(e,t,n,i){if(!r[e.id])r[e.id]={};if(!r[e.id][t])r[e.id][t]={};if(!r[e.id][t][n])r[e.id][t][n]=[];r[e.id][t][n].push(i)}function l(e,t,n,i){if(!i&&!n){r[e.id][t]={};return}if(!i){delete r[e.id][t][n];return}for(var s=0;s<r[e.id][t][n].length;s++)if(r[e.id][t][n][s]===
i){r[e.id][t][n].pop(s,1);break}}function c(e,n,s){if(!r[e][s])return;var o=n.target||n.srcElement,u,f,l={},c=0,h=0;t=0;for(u in r[e][s])if(r[e][s].hasOwnProperty(u)){f=a(o,u,i[e].element);if(f&&p.matchesEvent(s,i[e].element,f,u=="_root",n)){t++;r[e][s][u].match=f;l[t]=r[e][s][u]}}n.stopPropagation=function(){n.cancelBubble=true};for(c=0;c<=t;c++)if(l[c])for(h=0;h<l[c].length;h++){if(l[c][h].call(l[c].match,n)===false){p.cancel(n);return}if(n.cancelBubble)return}}function h(e,t,n,i){function u(e){return function(t){c(s,
t,e)}}if(!(e instanceof Array))e=[e];if(!n&&typeof t=="function"){n=t;t="_root"}var s=this.id,o;for(o=0;o<e.length;o++){if(!r[s]||!r[s][e[o]])p.addEvent(this,e[o],u(e[o]));if(i){l(this,e[o],t,n);continue}f(this,e[o],t,n)}return this}function p(e,t){if(typeof e=="string"&&typeof t=="function"||typeof t=="string")p(document).on(arguments[0],arguments[1],arguments[2],arguments[3]||false);if(!(this instanceof p)){for(var r in i)if(i[r].element===e)return i[r];n++;i[n]=new p(e,n);i[n]._on=i[n].on;i[n].on=
function(e,t,n,r){var i=typeof t=="function"?t:n,s=typeof t=="function"?n||false:r||false;if(!s)return this._on.call(this,e,t,n);else{var o=[e];if(typeof t=="string")o.push(t);o.push(function(e){return function(t){if(!t.defaultPrevented)Bootstrapper.Delegate.load(this,s);if(typeof t.preventDefault!="undefined")t.preventDefault();else t.returnValue=false;e.call(this)}}(i));this._on.apply(this,o)}};return i[n]}this.element=e;this.id=t}var e,t=0,n=0,r={},i={};_delay=750;p.prototype.on=function(e,t,n){return h.call(this,
e,t,n)};p.prototype.off=function(e,t,n){return h.call(this,e,t,n,true)};p.matchesSelector=function(){};p.cancel=o;p.addEvent=s;p.matchesEvent=function(){return true};p.load=function(e,t){var n=typeof t=="number"?parseInt(t):750;setTimeout(function(e,t){return function(){if(e.nodeName&&"a"==e.nodeName.toLowerCase()){if(t&&/^javascript\s*\:/.test(t))return(new Function(unescape(t))).call(window);else if(e.target&&/_blank|_new/i.test(e.target))return true;if(t)window.location.href=t}}}(e,e.href||""),
n)};Bootstrapper.Delegate=p})();(function(e){var t=e.addEvent;e.addEvent=function(e,n,r){if(e.element.addEventListener)return t(e,n,r);if(n=="focus")n="focusin";if(n=="blur")n="focusout";e.element.attachEvent("on"+n,r)};e.simpleMatchesSelector=function(e){if(e.charAt(0)===".")return(" "+this.className+" ").indexOf(" "+e.slice(1)+" ")>-1;if(e.charAt(0)==="#")return this.id===e.slice(1);return this.tagName.toUpperCase()===e.toUpperCase()};e.matchesSelector=function(t){if(!~t.indexOf(" ")&&!~t.indexOf("\x3e"))return e.simpleMatchesSelector.call(this,
t);else{var n=this,r=t.split(" ").reverse();while(r.length){var i=r.shift();if(~i.indexOf("\x3e")){i=i.split("\x3e").reverse();while(i.length){tempSel=i.shift();if(e.simpleMatchesSelector.call(n,tempSel))n=n.parentNode;else return false}if(!r.length)return true}else while(n!=document){var s=e.simpleMatchesSelector.call(n,i);n=n.parentNode;if(s){if(!r.length)return true;break}}}return false}};e.cancel=function(e){if(e.preventDefault)e.preventDefault();if(e.stopPropagation)e.stopPropagation();e.returnValue=
false;e.cancelBubble=true}})(Bootstrapper.Delegate);Bootstrapper.on=Bootstrapper.Delegate;document.getElementsByClassName=document.getElementsByClassName||function(b){var c=this.all||this.getElementsByTagName("*"),d=[];b=RegExp("(?:^|\\s)"+b+"(?:\\s|$)");for(var a=0;a<c.length;a++)b.test(c[a].className)&&d.push(c[a]);return d};Bootstrapper.getQueryParam=function(key,loc){if(!this.params||loc){var search=loc||window.location.search;var params=search.replace(/^\?/,""),paramObj={};params=params.split("\x26");
for(var i=0;i<params.length;i++){var t=params[i].split("\x3d");paramObj[t[0]]=t[1]}if(!loc)this.params=paramObj;else return paramObj[key]||""}return this.params[key]||""};Bootstrapper.getElementXPath=function(e){var n=e;var p="";while(n!=document.getElementsByTagName("html")[0]){var t="/"+n.tagName;if(n.id!=""){t+="#"+n.id;p=t+p}else{var c=1;_n=n.previousSibling;while(_n!=null){if(n.tagName==_n.tagName)c++;_n=_n.previousSibling}p=t+(c!=1?"["+c+"]":"")+p}n=n.parentNode}return Bootstrapper.getMinXPath("/HTML"+
p)};Bootstrapper.getMinXPath=function(path){var p=path.split("/"),lastId=0;for(var i=0;i<p.length;i++)if(~p[i].indexOf("#"))lastId=i;for(var i=lastId-1;i>0;i--)if(!p[i].match(/^(html|body)/i))p.splice(i,1);return p.join("/")};Bootstrapper.getElementByXPathStep=function(d,a){var c=~a.indexOf("#")?a.split("#")[1]:"",e=c?0:~a.indexOf("[")?parseInt(a.match(/\[(\d+)\]/)[1]):0,f=(c?a.split("#")[0]:e?a.split("[")[0]:a).toLowerCase();if(d==document&&f=="html"&&e==0)return document.getElementsByTagName("html")[0];
if(~a.indexOf("#"))return document.getElementById(a.split("#")[1]);var b=d.firstChild;if(!b)return null;for(var g=0,e=e!=0?e-1:e;b;){if(b.nodeType==1)if(b.tagName.toLowerCase()==f&&c!=""&&b.id==c)return b;else if(b.tagName.toLowerCase()==f&&g==e&&c=="")return b;else b.tagName.toLowerCase()==f&&g++;b=b.nextSibling}};Bootstrapper.getElementByXPath=function(d,n){for(var d=d.split("/"),a=Bootstrapper.getElementByXPathStep(n||document,d[1]),c=2;c<d.length;c++){if(a==null)return null;a=Bootstrapper.getElementByXPathStep(a,
d[c])}return a};window._log=function(m){window._enslog=window._enslog||[];window._enslog.push(m);if(console){var v=typeof m=="string"?m:"",s=window.location.search,p=~s.indexOf("ensightenDebug\x3d")?s.split("ensightenDebug\x3d")[1].split("\x26")[0].split("#")[0].split(";")[0]:!1;if(p&&p=="act"){if(~v.indexOf("$$$"))console.log(v)}else if(p&&p=="cloak"){if(~v.indexOf("*** Cloak"))console.log(v)}else if(p)console.log(m)}};Bootstrapper.MVT=function(){var g={},h={split:function(b,a){var c=[];do{var d=
b.shift(),e=[],f=[d];(e=d.x.split("/")).shift();for(d=b.length-1;-1<d;d--){var g=b[d].x.split("/");g.shift();g[0]==e[0]&&(f.push(b[d]),b.splice(d,1))}c.push(f)}while(0<b.length);for(d=0;d<c.length;d++)e=this.getCommon(c[d]),Bootstrapper.MVT.traverse(a,e,c[d])},getCommon:function(b){for(var a=[],c=0;c<b.length;a.push(b[c++].x));if(1==a.length)return a[0];for(c=0;c<a.length;(a[c]=a[c++].split("/")).shift());b=a[0];for(c=1;c<a.length;c++){for(var d=0;d<a[c].length;d++)if(a[0][d]!=a[c][d]){var e=d;break}if(e)break}return"/"+
b.slice(0,e).join("/")},tests:[]},i={hidden:[],cloaks:[],EDLutils:!0,initialized:!1,invisibilityCloak:!1,disabled:!!~window.location.search.indexOf("ensTools\x3ddisable"),cloakDisabled:(true||!!~window.location.search.indexOf("ensCloak\x3ddisable"))&&!~window.location.search.indexOf("ensCloak\x3denable"),forceSyncCloak:!!~window.location.search.indexOf("ensCloak\x3d")&&!!~window.location.search.indexOf("!resync"),content:{initialized:!1,map:{},list:"",target:function(o){if(typeof o=="string"&&~o.indexOf("##")&&
~o.indexOf("@@"))this.store(o);else{if(o instanceof Array){var c="";for(var i=0,l=o.length;i<l;i++)if(o[i].u)c+="##"+o[i].u+"@@"+(o[i].x||"")}else if(o.u)o="##"+o.u+"@@"+(o.x||"");this.store(o)}},utils:function(a,n,o){if(Bootstrapper.data)try{if(a=="get")return Bootstrapper.data.getEngine("store").utils.get(n);else if(a=="set")return Bootstrapper.data.getEngine("store").utils.set(n,o)}catch(e){Bootstrapper.MVT.EDLutils=false;_log("*** Cloak:EDL utils not available")}else{Bootstrapper.MVT.EDLutils=
false;_log("*** Cloak:EDL not available")}},store:function(o){if(!Bootstrapper.MVT.content.initialized)this.list=o;else{if(this.list=="")this.list=o;this.utils("set","_ensCloak",o)}_log("*** Cloak:Storage updated")},load:function(d){var cl;if(d==1)cl=this.list;else cl=this.utils("get","_ensCloak");if(!d){_log("GLOBAL: "+this.list);_log("STORED: "+cl)}if(typeof cl=="string"&&cl!=""&&~cl.indexOf("##")){cl=cl.split("##");for(var i=0,l=cl.length;i<l;i++)if(~cl[i].indexOf("@@")){var u=cl[i].split("@@")[0],
x=cl[i].split("@@")[1]||"";if(d=="list"){_log("URL: "+u);_log("XPATH: "+x)}this.add({"u":u,"x":x})}_log("*** Cloak:Storage loaded")}else _log("*** Cloak:Storage empty")},add:function(o){if(o.u){if(~window.location.href.indexOf(o.u))if(o.x&&o.x!=""){if(typeof this.map[o.x]=="undefined"){this.map[o.x]=o;this.map[o.x].t="map"}}else Bootstrapper.MVT.invisibilityCloak=true}else if(typeof this.map[o.x]=="undefined"){this.map[o.x]=o;this.map[o.x].t="map"}},init:function(){if(!Bootstrapper.MVT.cloakDisabled){var sync=
this.utils("get","_ensCloakSync")||"",time=(new Date).getTime(),fetch=true;if(Bootstrapper.MVT.EDLutils){if(~sync!=""&&!isNaN(sync))if(time-sync>18E5)sync=time;else fetch=false;else sync=time;if(fetch)this.utils("set","_ensCloakSync",sync)}else fetch=false;if(fetch||Bootstrapper.MVT.forceSyncCloak){if(Bootstrapper.scDataObj)Bootstrapper.scDataObj["ensCloak"]="sync";if(this.list=="")Bootstrapper.MVT.invisibilityCloak=true;_log("*** Cloak:Syncing")}this.load(1);this.load(2)}var m=this.map;for(i in m)if(m[i].x)Bootstrapper.MVT.push({x:m[i].x,
m:m[i].x,t:"map"});if(Bootstrapper.MVT.invisibilityCloak&&!Bootstrapper.MVT.disabled&&!Bootstrapper.MVT.cloakDisabled)Bootstrapper.MVT.cover()}},addModule:function(b,a){g[b]=a},swap:function(b,a){g[a.t].swap(b,a)},start:function(b){for(var a=0;a<b.length;a++)g[b[a].t].init(b[a]);a=h.getCommon(b);"/"==a&&h.split(b,document);this.traverse(document,a,b)},init:function(){Bootstrapper.MVT.content.initialized=!0;Bootstrapper.MVT.content.init();_log("*** MVT:init - "+h.tests.length+" targets");Bootstrapper.MVT.initialized=
!0;_log(h.tests.slice());if(h.tests.length&&!this.disabled)Bootstrapper.MVT.start(h.tests)},push:function(o){if(Bootstrapper.MVT.disabled)return;if(typeof o=="object"){_log("*** MVT:push");_log(o);if(typeof this.setDone=="undefined"){this.setDone=1;Bootstrapper.bindPageSpecificCompletion(function(){Bootstrapper.MVT.done()});Bootstrapper.bindDOMLoaded(function(){setTimeout(function(){Bootstrapper.MVT.done()},500)})}if(o.x){o.cloak=this.cloak(o,1);if(o.t&&this.content.map[o.x])if(o.t=="map")this.content.map[o.x].cloak=
o.cloak;else if(this.content.map[o.x].cloak)Bootstrapper.MVT.delCSS(this.content.map[o.x].cloak)}if(this.initialized&&o.x){_log("MVT:content");_log(o);if(this.content.map[o.x])for(i in o)this.content.map[o.x][i]=o[i];else this.check(o)}else{for(var i=0;i<h.tests.length;i++)if(h.tests[i].x&&o.x&&h.tests[i].x==o.x)if(h.tests[i].t=="map"&&o.t!="map"){for(j in o)h.tests[i][j]=o[j];return}h.tests.push(o);this.hidden.push(o)}}},injectCSS:function(x,e){var d=document,s=d.createElement("style");if(e)s.className=
"_ensCSS";if("\v"=="v"){d.getElementsByTagName("head")[0].appendChild(s);s.styleSheet.cssText=x}else{s.type="text/css";s.innerHTML=x;d.getElementsByTagName("head")[0].appendChild(s)}return s},delCSS:function(s,f){if(s)try{if("\v"=="v")s.styleSheet.cssText="/**/";if(s.parentNode)s.parentNode.removeChild(s);return!0}catch(e){if(f)return f();return!1}return!1},cover:function(){_log("*** Cloak:Cover");this.invisibilityCloak=this.injectCSS("body{position:relative; opacity:0 !important;filter:alpha(opacity\x3d0) !important;background:none !important}");
Bootstrapper.bindPageSpecificCompletion(function(){Bootstrapper.MVT.uncover("Uncover - complete")});Bootstrapper.bindDOMLoaded(function(){setTimeout(function(){Bootstrapper.MVT.uncover("Uncover - loaded")},500)});setTimeout(function(){Bootstrapper.MVT.uncover("Uncover - timeout")},7E3)},uncover:function(l){if(this.invisibilityCloak)if(this.delCSS(this.invisibilityCloak)){this.invisibilityCloak=!1;_log("*** Cloak:"+l)}},cloak:function(o,t){var s=false,x=o.toString();if(typeof o=="object"&&o.x)x=o.x;
if(~x.indexOf("/HTML/"))x=x.substr(1).replace(/\//g," ").replace(/\[.*\]$/g,"");s=Bootstrapper.MVT.injectCSS(x+"{visibility:hidden !important}",t);if(t)this.cloaks.push(s);return s},show:function(a,b){if(b&&b.cloak)this.delCSS(b.cloak);else if(a){a.style.display=a.style.oldDisplay||"block";a.style.visibility="visible"}},done:function(){var a=this.hidden,c=this.cloaks,s=document.getElementsByTagName("style");for(i=0;i<h.length;i++)this.show(h[i]);this.hidden=[];for(i=0;i<c.length;i++)this.delCSS(c[i]);
this.cloaks=[];for(i=0;i<s.length;i++)if(s[i].className=="_ensCSS")this.delCSS(s[i]);_log("*** MVT:done")},check:function(o){var n=Bootstrapper.getElementByXPath(o.x);_log("*** MVT:check");_log(n);if(n)Bootstrapper.MVT.swap(n,o);else if(!Bootstrapper.hasDOMLoaded())setTimeout(function(){Bootstrapper.MVT.check(o)},25);else{setTimeout(function(){Bootstrapper.MVT.done()},100);_log("*** MVT:unresolved - not found")}},traverse:function(b,a,c){if(1==c.length&&c[0].x==a)var d=!0;for(var e=0;e<c.length;c[e].x=
c[e++].x.slice(a.length));(a=a.split("/")).shift();for(e=0;e<a.length;e++){var f=Bootstrapper.getElementByXPathStep(b,a[e]);if(null!=f){Bootstrapper.swapNodes=Bootstrapper.swapNodes||[];Bootstrapper.swapNodes.push(f);b=f}else{a="/"+a.slice(e).join("/");for(e=0;e<c.length;c[e].x=a+c[e++].x);if(!Bootstrapper.hasDOMParsed()){setTimeout(function(a,b,c){return function(){Bootstrapper.MVT.traverse(a,b,c)}}(b,a,c),25);return}else{setTimeout(function(){Bootstrapper.MVT.done()},100);_log("*** MVT:unresolved - not found");
return}}}d?this.swap(b,c[0]):h.split(c,b)}};return i}();Bootstrapper.bindOnGetServerComponent(function(){Bootstrapper.MVT.init()});Bootstrapper.MVT.addModule("map",{init:function(a){},swap:function(a,b){if(typeof Bootstrapper.DOMloadedDone=="undefined"||!Bootstrapper.DOMloadedDone){if(Bootstrapper.hasDOMLoaded()&&typeof Bootstrapper.DOMloadedDone=="undefined"){Bootstrapper.DOMloadedDone=!1;_log("*** DOM:loaded ***");setTimeout(function(){Bootstrapper.DOMloadedDone=!0},500)}if(Bootstrapper.MVT.content.map[b.m].t!=
"map"){for(i in Bootstrapper.MVT.content.map[b.m])b[i]=Bootstrapper.MVT.content.map[b.m][i];Bootstrapper.MVT.swap(a,b);return}else{setTimeout(function(){Bootstrapper.MVT.swap(a,b)},10);return}}else{_log("*** MVT:show - no changes found \x3d "+b.m);Bootstrapper.MVT.show(a,b)}}});Bootstrapper.MVT.addModule("xp",{init:function(a){},swap:function(a,b){_log("*** MVT:loaded");_log(a);_log(b);var d=0;if(b.p=="replace"){if(!a.tagName.toUpperCase().match(/IMG|INPUT|TEXTAREA/)){a.innerHTML=b.c;a.className=
a.className+" ensContent";d=a}}else{d=document.createElement("div");d.className="ensContent";d.innerHTML=b.c;if(b.p=="prepend")if(a.firstChild!==null)a.insertBefore(d,a.firstChild);else d=0;else if(b.p=="append")a.appendChild(d,a);else if(b.p=="element")if(a.parentNode!==null)a.parentNode.replaceChild(d,a);else d=0;else if(b.p=="before")if(a.parentNode!==null)a.parentNode.insertBefore(d,a);else d=0;else if(b.p=="after")if(a.parentNode!==null)if(a.nextSibling===null)a.parentNode.appendChild(d);else a.parentNode.insertBefore(d,
a.nextSibling);else d=0}try{if(d)for(var s=d.getElementsByTagName("script"),l=s.length,i=0;i<l;i++)if(s[i].src){var l=document.createElement("script");l.src=s[i].src;l.type=s[i].type;s[i].parentNode.replaceChild(d,s[i])}else Function("try{"+s[i].text+"}catch(e){}")()}catch(e){}_log("*** MVT:complete");Bootstrapper.MVT.show(a,b)}});Bootstrapper.VTconfig=Bootstrapper.VTconfig||{};Bootstrapper.VTconfig["MVT"]=this.deploymentId;Bootstrapper.propertyWatcher=function(options){var _private={watchers:[]},
_public={};_private.options=options||{};_private.options.interval=_private.options.interval||50;_private.Watcher=function(propertyFn,options){var _public={};_public.propertyFn=propertyFn;_public.lastValue=undefined;_public.options=options;_public.change=function(oldVal,newVal){};return _public};_private.doChecks=function(){for(var i=0;i<_private.watchers.length;i++){var w=_private.watchers[i],p=w.propertyFn?w.propertyFn():null;if(w.lastValue!=p){w.change(w.lastValue,p);w.lastValue=p}}_private.resetTimer()};
_private.resetTimer=function(){window.setTimeout(function(){_private.doChecks()},_private.options.interval)};_private.addWatcher=function(fn,options){var w=_private.Watcher(fn,options);_private.watchers.push(w);return w};_public={create:_private.addWatcher};_private.doChecks();return _public}();Bootstrapper.safeIframeInsert=function(u){var newFrame=document.createElement("iframe");newFrame.src=u;newFrame.width=newFrame.height="1px";newFrame.style.display="none";var rand=parseInt(1E5*1E4*Math.random()*
Math.random());Bootstrapper["appendFrame"+rand]=setInterval(function(a,b){return function(){document.getElementsByTagName("body")&&0<document.getElementsByTagName("body").length&&(clearInterval(Bootstrapper["appendFrame"+b]),document.getElementsByTagName("body")[0].appendChild(a))}}(newFrame,rand),250)};Bootstrapper.trim=function(str){return str.replace(/^\s+|\s+$/g,"")};Bootstrapper.fnIsEmpty=function(fn){try{if(fn){var rx=/^function [^(]*\(\)[ ]*{(.*)}$/;var b=rx.exec((fn+"").replace(/\n/g,""))[1];
return Bootstrapper.trim(b)===""}else return true}catch(err){console.info(err);return false}};Bootstrapper.parseHTML=function(c){var d,b,a,e=!1,g=[];d=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi;var h=/<([\w:]+)/;a=/<|&#?\w+;/;b={option:[1,"\x3cselect multiple\x3d'multiple'\x3e","\x3c/select\x3e"],legend:[1,"\x3cfieldset\x3e","\x3c/fieldset\x3e"],thead:[1,"\x3ctable\x3e","\x3c/table\x3e"],tr:[2,"\x3ctable\x3e\x3ctbody\x3e","\x3c/tbody\x3e\x3c/table\x3e"],td:[3,"\x3ctable\x3e\x3ctbody\x3e\x3ctr\x3e",
"\x3c/tr\x3e\x3c/tbody\x3e\x3c/table\x3e"],col:[2,"\x3ctable\x3e\x3ctbody\x3e\x3c/tbody\x3e\x3ccolgroup\x3e","\x3c/colgroup\x3e\x3c/table\x3e"],area:[1,"\x3cmap\x3e","\x3c/map\x3e"]};b.optgroup=b.option;b.tbody=b.tfoot=b.colgroup=b.caption=b.thead;b.th=b.td;b._default=[1,"X\x3cdiv\x3e","\x3c/div\x3e"];f=document;if("string"==typeof c)if(a.test(c)){if(!(a=e))if(a=f,e="abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video".split(" "),
a=a.createDocumentFragment(),a.createElement)for(;e.length;)a.createElement(e.pop());e=a;a=f.createElement("div");e.appendChild(a);c=c.replace(d,"\x3c$1\x3e\x3c/$2\x3e");d=(h.exec(c)||["",""])[1].toLowerCase();b=b[d]||b._default;d=b[0];for(a.innerHTML=b[1]+c+b[2];d--;)a=a.lastChild;c=a.childNodes;a.parentNode.removeChild(a)}else c=f.createTextNode(c);if(c.nodeType)g.push(c);else{b=c.length;d=g.length;a=0;if("number"==typeof b)for(;a<b;a++)g[d++]=c[a];else for(;c[a]!==h;)g[d++]=c[a++];g.length=d}return g};
document.write=function(){var parse=Bootstrapper.parseHTML,parseHTML,head,target,tail,open=false,lastString="",lastNodes=[],configTarget=function(){if(document.getElementById("_ensDiv")===null){var d=document.createElement("div");d.style.display="none";d.id="_ensDiv";document.body.appendChild(d);target=d;return}target=document.getElementById("_ensDiv")};return function(x){if(target===undefined)configTarget();if(open){open=false,newS=lastString+x;newN=parse(newS);for(var i=newN.length-1;i>-1;i--)if(lastNodes[i]&&
newN[i].outerHTML==lastNodes[i].outerHTML)newN.splice(i,1);target.removeChild(tail);for(var i=0;i<newN.length;i++)document.body.appendChild(newN[i]);nodes=newN}var nodes=nodes||parse(x);for(var i=0;i<nodes.length;i++){if(nodes[i].nodeName=="SCRIPT"){var n=document.createElement("script");for(var k in nodes[i])try{if(typeof nodes[i][k]=="string"&&nodes[i][k]!=n[k]&&!/html$/i.test(k))n.setAttribute(k,nodes[i][k]);else if(typeof nodes[i][k]=="function"&&nodes[i][k]!=n[k])n[k]=nodes[i][k]}catch(e){}nodes[i]=
n}target.appendChild(nodes[i]),tail=nodes[i]}if(tail.nodeType==1&&!/\>$/.test(x)){open=true;lastString=x;lastNodes=nodes}}}();window.analytics=window.analytics||{};window.analytics.utilities=window.analytics.utilities||{};var util=window.analytics.utilities,_;_={truncateString:function(str){var desiredLength=100;return str.length>desiredLength?str.substring(0,desiredLength-3)+"...":str}};window.analytics.utilities={setWEDCSAttributes:function(element,wedcsAttributes){var dataAttributes=window.analytics.utilities.dataAnalyticsAttributes(element),
merged=jQuery.extend(wedcsAttributes,dataAttributes),prepared=window.analytics.utilities.prepareAttributes(merged);element.attr(prepared)},dataAnalyticsAttributes:function(element){var elementHasDataAnalyticsTag=element.is("[data-analyticstag]"),parsed={};if(elementHasDataAnalyticsTag){var dataAnalyticsAttributeArray=jQuery.trim(element.attr("data-analyticstag")).split("_"),linkType=dataAnalyticsAttributeArray.slice(0,3);if(linkType.join(""))parsed.link_type=linkType.join(":");parsed.index=dataAnalyticsAttributeArray[4].match(/\d/).join("");
parsed.cmpgrp=dataAnalyticsAttributeArray[3]}return parsed},prepareAttributes:function(object){var prepared={},key;for(key in object)if(object.hasOwnProperty(key))prepared["ms."+key]=_.truncateString(jQuery.trim(object[key]));return prepared},getMetaTagContent:function(metaName){return jQuery('meta[name\x3d"'+metaName+'"]').attr("content")},mscomCustomEventBuilder:function(wedcsAttributes){var msComEventArray=[],wedcskey;for(wedcskey in wedcsAttributes)if(wedcsAttributes.hasOwnProperty(wedcskey))msComEventArray.push(wedcskey,
_.truncateString(jQuery.trim(wedcsAttributes[wedcskey])));window.MscomCustomEvent.apply(this,msComEventArray)},readCookie:function(cookieName){var nameEQ=cookieName+"\x3d",ca=document.cookie.split(";"),i,c;for(i=0;i<ca.length;i++){c=ca[i];while(c.charAt(0)===" ")c=c.substring(1,c.length);if(c.indexOf(nameEQ)===0)return c.substring(nameEQ.length,c.length)}return null},validateCookie:function(cookieName,cookieValue){var cookie=decodeURI(window.analytics.utilities.readCookie(cookieName));return!cookie||
cookie.indexOf(cookieValue)===-1?false:true},getParameterByName:function(name){var match=(new RegExp("[?\x26]"+name+"\x3d([^\x26]*)")).exec(window.location.search);return match&&decodeURIComponent(match[1].replace(/\+/g," "))},setMetaTag:function(name,content){var metaNode=document.createElement("meta"),s=document.getElementsByTagName("script");metaNode.name=name;metaNode.content=content;if(s.length){s=s[0];s.parentNode.insertBefore(metaNode,s)}},getPageTemplate:function(){return jQuery("#content \x3e div").attr("id")}}},
1174545,361052);
Bootstrapper.bindDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var pagetype=jQuery('meta[name\x3d"ms.sitesec"]').attr("content");var site=jQuery('meta[name\x3d"ms.ea_targetcampaign"]').attr("content");var e=document.createElement("script");e.async=true;e.src="https://ad.atdmt.com/m/a.js;m\x3d11087206429758;cache\x3d"+Math.random()+"?";var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(e,s);function atlasTrack(uri){var timestamp=new Date;
var qs="\x26random\x3d"+Math.ceil(Math.random()*99999999)+timestamp.getUTCFullYear()+timestamp.getUTCMonth()+timestamp.getUTCDate()+timestamp.getUTCHours()+timestamp.getUTCMinutes()+timestamp.getUTCSeconds()+timestamp.getUTCMilliseconds();var uriPlus="//ad.atdmt.com/m/a.js;m\x3d11087206429758?event\x3d"+uri+qs;var script=document.createElement("script");script.type="text/javascript";script.src=uriPlus;document.getElementsByTagName("head")[0].appendChild(script)}if(site==="CP2-WE-1C-203457")if(pagetype===
"LandingPage")atlasTrack("DND_Dynamics_ITA_Ent_Sit_DynamicsEventFORM_LP");else if(pagetype==="ThankYouPage")atlasTrack("DND_Dynamics_ITA_Ent_Sit_DynamicsEventTHKU_CON")},1272161,373160);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();